Replace Dockge with Portainer, rename homeapi to api, update api routes and github deploy workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -49,7 +49,6 @@ jobs:
             - name: Checkout code
               uses: actions/checkout@v3
 
-            # Deploy to homelab over Tailscale SSH
             - name: Connect Tailscale
               uses: tailscale/github-action@v3
               with:
@@ -59,21 +58,20 @@ jobs:
             - name: Deploy to server
               run: |
                   curl -s http://homelab:5001/tasks/run/deploy
-                  for i in {1..60}; do
-                    echo "Polling server - attempt $i/60"
-                    RESP=$(curl -s http://homelab:5001/maintenance/status)
-                    VERSION=$(echo $RESP | jq -r .version)
-                    STATUS=$(echo $RESP | jq -r .status)
 
-                    if [ "$VERSION" = "$EXPECTED_SHA" ] && [ "$STATUS" = "success" ]; then
-                        echo "Deploy succeeded"
-                        exit 0
-                    fi
+            - name: Wait for heartbeat
+              run: |
+                  echo "Waiting 60s..."
+                  sleep 60
 
-                    sleep 5
-                  done
+            - name: Check server health
+            - run: |
+                  status_code=$(curl -s -o /dev/null -w "%{http_code}" http://homelab:5001)
 
-                  echo "Deploy failed - timed out"
-                  echo "Status: $STATUS"
-                  echo "Commit SHA: $VERSION, Expected: $EXPECTED_SHA"
-                  exit 1
+                  if [ "$status_code" -ne 200 ]; then
+                    echo "Deployment health check failed: HTTP $status_code"
+                    exit 1
+                  else
+                    echo "Deployment succeeded."
+                    exit 0
+                  fi
